parameters:  
  location: 'westeurope'

steps:
- download: current
  artifact: build
- download: current
  artifact: arm
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Pipeline.Workspace)/arm/deploy.ps1'
    arguments: '-location ${{ parameters.location }}'    
  
- task: AzureFunctionApp@1
  displayName: Deploy Function App
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN'
    appType: 'functionApp'
    appName: $(name)-$(System.StageName)-${{ parameters.location }}
    package: '$(Pipeline.Workspace)/build/app.zip'
    deploymentMethod: 'auto'
