# Build Number
name: $(Date:yyyyMMdd)$(Rev:.r)
# -------------------------------------------------------------------------------

trigger:
- feature/*
- hotfix/*
- refs/tags/*

variables:
   name: engage2019

stages:      
  - stage: build
    displayName: Build    
    jobs:    
      - job:    
        displayName: 'Build Application'  
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet restore"
            inputs:
              command: 'restore'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: 'build'
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: 'test'
          - task: DotNetCoreCLI@2
            displayName: "dotnet publish"
            inputs:
              command: 'publish'
              publishWebProjects: false
              arguments: '--configuration Release --output $(Pipeline.Workspace)/app --no-restore'
              modifyOutputPath: false
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)/app'
              artifact: 'build'
              publishLocation: 'pipeline'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'templates/deploy.ps1'
              artifact: 'arm'
              publishLocation: 'pipeline'
          
  - stage: dev
    displayName: Development
    dependsOn: build
    jobs:
    - deployment: Development      
      environment: DEV
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.functions.yml
              parameters: 
                name: $name
  - stage: integrationtests
    displayName: Integration Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.tests.yml
  - stage: componenttests
    displayName: Component Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.tests.yml
  - stage: endtoendtests
    displayName: End-To-End Tests
    dependsOn: dev
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.tests.yml
  - stage: uat
    displayName: UAT
    dependsOn: 
    - componenttests
    - integrationtests
    - endtoendtests
    jobs:
    - deployment: Testing      
      environment: TEST
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.functions.yml
              parameters: 
                name: $name
  - stage: canary
    displayName: Production Canary
    dependsOn: uat
    jobs:
    - deployment: canary      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.functions.yml
              parameters: 
                name: $name
  - stage: ea
    displayName: Production EarlyAdopters
    dependsOn: canary
    jobs:
    - deployment: ea      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.functions.yml
              parameters: 
                name: $name
  - stage: prod
    displayName: Production Live
    dependsOn: ea
    jobs:
    - deployment: prod      
      environment: PROD
      timeoutInMinutes: 60
      strategy: 
        runOnce:
          deploy:          
            steps:
            - template: azure-pipelines.functions.yml
              parameters: 
                name: $name